### ISSUE TITLE
remark-lint failures don't fail the build

### ISSUE THREAD

**Issue by asbjornu** [prologic/action-remark-lint#2]
Either, `remark-lint` don't exit with a non-zero exit code on failures, or the exit code is not propagated to GitHub Actions. Either way, [I have 82 failures in one of my builds](https://github.com/SwedbankPay/swedbank-pay-design-guide-jekyll-theme/pull/129/checks?check_run_id=816507667#step:4:909) and it's still marked as successful.

**Comment by prologic** [comment]
Can you put a PR top fix this?

**Comment by asbjornu** [comment]
I would love to, @prologic. Do you have any ideas why the exit code of the action is `0` even though `remark-lint` fails? Is it `reviewdog` that mask the exit code somehow?

**Comment by prologic** [comment]
> I would love to, @prologic. Do you have any ideas why the exit code of the action is `0` even though `remark-lint` fails? Is it `reviewdog` that masks the exit code somehow?

I don't know off the top of my head. I'd suspect its the underlying tool is returning a non-sense exit status. If that's the case; that should be fixed upstream; I doubt it would be reviewdog itself at fault here...

**Comment by asbjornu** [comment]
@prologic, I believe I've fixed the problem in #3.
